import type { Metadata } from "next";
import { Cairo, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";

const cairo = Cairo({
  variable: "--font-cairo",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body
        className={`${cairo.className} ${cairo.variable} ${geistMono.variable} antialiased`}
      >
        <div className="fixed top-0 inset-x-0 z-50 !w-full backdrop-blur-sm bg-white/80">
          <Header />
        </div>
        <div className="h-20"></div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
